version: "3.8"

services:
  rahoot:
    build: .
    image: rahoot-local
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/app/config # Path to your game config
    environment:
      - WEB_ORIGIN=localhost:3000
      - SOCKET_URL=localhost:3001
      - DATABASE_URL=postgresql://webtutor:eUukMVHNK8@dc0-prod-webtutor-pgsql-01.esoft.local:5432/edu?sslmode=require
